### ISSUE TITLE
Report error“PublicKeyCredential is not defined” when registering in Android Chrome

### ISSUE THREAD

**Issue by wf-chen** [line/line-fido2-server#37]
I deploy the project on the Windows 
![image](https://user-images.githubusercontent.com/55571666/216013548-b76f18cb-7703-45d9-8740-bc406a130022.png)

**Comment by kkk6285137** [comment]
I have the same problem. I didn't really solve it. maybe I can provide some ideas.

I encountered this problem on the Windows system and Android phone. However, on Linux, this issue did not occur, and I completed the authentication. So I suspect that this issue is related to the system. Perhaps your current Windows system and Android phone do not support this feature yet. Attempt to upgrade or replace the system?

**Comment by wf-chen** [comment]
> I have the same problem. I didn't really solve it. maybe I can provide some ideas.
> 
> I encountered this problem on the Windows system and Android phone. However, on Linux, this issue did not occur, and I completed the authentication. So I suspect that this issue is related to the system. Perhaps your current Windows system and Android phone do not support this feature yet. Attempt to upgrade or replace the system?

Ok，thanks for advice.

**Comment by wf-chen** [comment]
> > I have the same problem. I didn't really solve it. maybe I can provide some ideas.
> > I encountered this problem on the Windows system and Android phone. However, on Linux, this issue did not occur, and I completed the authentication. So I suspect that this issue is related to the system. Perhaps your current Windows system and Android phone do not support this feature yet. Attempt to upgrade or replace the system?
> 
> Ok，thanks for advice.
